### PR TITLE
Bump Docusaurus version to fix @babel/compat-data error on build

### PR DESCRIPTION
**Pull request by acostalima**
Related:
- https://github.com/nodejs/node/issues/32852
- https://github.com/moxystudio/babel-preset/pull/50
- https://github.com/moxystudio/react-native-with-moxy/pull/40

### CODE REVIEW

**Comment by satazor** [comment]
Screenshot 2020-06-15 at 21 01 00

We need to check if we are using these classes in our custom css styles.

**Comment by acostalima** [comment]
@satazor, I've scanned the changelog from `2.0.0-alpha.48` to `2.0.0-alpha.56` and it seems the only breaking change for us renaming `--ifm-font-base-color` to `--ifm-font-color-base`.

**Comment by satazor** [comment]
Cool! Will merge.

Can you apply these changes to our private next-with-moxy recipes on GitLab?

**Comment by acostalima** [comment]
> Cool! Will merge.
> 
> Can you apply these changes to our private next-with-moxy recipes on GitLab?

Will do!

**Pull request merged**
